const elementsArray = [
  ['div', 'wrapper', 'wrapper'],
  ['header', 'header', 'header'],
  ['div', 'controls', 'controls'],
  ['button', 'controls__refresh', 'controlsRefresh'],
  ['p', 'controls__refresh_inner', 'controlsRefreshInner', null, null, null, null, null, null, '&#x27f3;'],
  ['select', 'controls__language', 'controlLanguage', 'language'],
  ['option', null, 'optionEN', null, 'en', null, null, null, null, 'EN'],
  ['option', null, 'optionRU', null, 'ru', null, null, null, null, 'RU'],
  ['option', null, 'optionBY', null, 'be', null, null, null, null, 'BY'],
  ['input', 'controls__input', 'Celsius', 'degree', 'C', 'radio'],
  ['label', 'controls__label', 'CelsiusLabel', null, null, null, null, 'Celsius', null, '&deg;C'],
  ['input', 'controls__input', 'Fahrenheit', 'degree', 'F', 'radio'],
  ['label', 'controls__label', 'FahrenheitLabel', null, null, null, null, 'Fahrenheit', null, '&deg;F'],
  ['div', 'search', 'search'],
  ['input', 'search__input', 'searchInput', null, null, 'search', null, null, 'City, Country'],
  ['button', 'search__microphone', 'searchMicrophone'],
  ['button', 'search__button', 'searchButton', null, null, null, null, null, null, 'search'],
  ['main', 'main', 'main'],
  ['div', 'weather-info', 'weatherInfo'],
  ['section', 'weather-today', 'weatherToday'],
  ['h1', 'weather-today__location', 'location'],
  ['p', 'weather-today__date', 'date'],
  ['p', 'weather-today__time', 'time'],
  ['div', 'weather-today__weather', 'weatherTodayWeather'],
  ['p', 'weather-today__weather_degree', 'weatherTodayDegree'],
  ['p', 'weather-today__weather_info', 'weatherTodayInfo'],
  ['section', 'weather-future', 'weatherFuture'],
  ['div', 'weather-future__item', 'weatherFutureItem1'],
  ['p', 'weather-future__item_day', 'weatherFuture1Day'],
  ['p', 'weather-future__item_temperature', 'weatherFuture1Temperature'],
  ['div', 'weather-future__item', 'weatherFutureItem2'],
  ['p', 'weather-future__item_day', 'weatherFuture2Day'],
  ['p', 'weather-future__item_temperature', 'weatherFuture2Temperature'],
  ['div', 'weather-future__item', 'weatherFutureItem3'],
  ['p', 'weather-future__item_day', 'weatherFuture3Day'],
  ['p', 'weather-future__item_temperature', 'weatherFuture3Temperature'],
  ['div', 'geo-info', 'geoInfo'],
  ['div', 'map', 'map'],
  ['p', 'zip', 'zip'],
];

export default elementsArray;
